version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot123
      POSTGRES_DB: task_manager_db
    volumes: 
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis

  web:
    build: .
    command: bash -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery

  celery:
    build: .
    command: bash -c "celery -A task_manager worker -l info -P gevent && celery -A task_manager beat -l info -S django"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:    
