# Generated by Django 4.1.7 on 2023-04-08 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_habit_slug_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='reward',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='progress_meter',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currency_amount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lvl',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='categories',
            field=models.ManyToManyField(null=True, to='registration.category'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_good',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='tracking_meter',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(null=True, to='registration.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
