# Generated by Django 4.1.7 on 2023-04-08 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_alter_achievement_reward_alter_category_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='habit',
        ),
        migrations.AddField(
            model_name='habit',
            name='difficulty',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='habit',
            name='negative_behavior_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='positive_behavior_count',
            field=models.IntegerField(default=0),
        ),
    ]
