# Generated by Django 4.1.7 on 2023-04-10 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_achievement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
