# Generated by Django 4.1.7 on 2023-04-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_task_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
    ]
