# Generated by Django 4.1.7 on 2023-05-08 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_remove_reward_image_remove_task_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
